plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		name = 'SmartBrainLib'
		url = 'https://dl.cloudsmith.io/public/tslat/sbl/maven/'
		content { includeGroup 'net.tslat' }
	}
	maven {
		name = 'GeckoLib'
		url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
		content { includeGroup 'com.geckolib' }
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"echo_warrior" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	runs {
		client {
			client()
			runDir 'run'
			programArg '--username=EchoWarriorDev'

			def quickPlayWorld = providers.gradleProperty('quickPlayWorld').orNull
			if (quickPlayWorld) {
				programArg '--quickPlaySingleplayer'
				programArg quickPlayWorld
			}
		}
		server {
			server()
			runDir 'run-server'
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation "net.tslat:smartbrainlib-fabric-${project.minecraft_version}:${project.smartbrainlib_version}"
	implementation "com.geckolib:geckolib-fabric-${project.minecraft_version}:${project.geckolib_version}"
}

processResources {
	inputs.property 'version', project.version

	filesMatching('fabric.mod.json') {
		expand 'version': project.version
	}

	from(rootProject.file('LICENSE')) {
		into 'META-INF'
		rename { 'LICENSE_ECHO_WARRIOR' }
	}
	from(rootProject.file('LICENSE-CODE')) {
		into 'META-INF'
		rename { 'LICENSE-CODE_ECHO_WARRIOR' }
	}
	from(rootProject.file('LICENSE-ASSETS.md')) {
		into 'META-INF'
		rename { 'LICENSE-ASSETS_ECHO_WARRIOR.md' }
	}
	from(rootProject.file('NOTICE')) {
		into 'META-INF'
		rename { 'NOTICE_ECHO_WARRIOR' }
	}
	from(rootProject.file('CREDITS.md')) {
		into 'META-INF'
		rename { 'CREDITS_ECHO_WARRIOR.md' }
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

publishing {
	publications {
		create('mavenJava', MavenPublication) {
			from components.java
		}
	}
}
