org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.1.3)
neo_form_version=26.1.2-1

loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.155.2+26.1.2

moddev_version=2.0.141
neoforge_version=26.1.2.100
neoforge_loader_version_range=[4,)

mod_version=0.1.1
maven_group=com.yuriscat
archives_base_name=echo-warrior
mod_id=echo_warrior
mod_name=Echo Warrior
mod_author=YurisCat Calypso
mod_credits=Tomato Fish, \u3010\uff1a\u3011
mod_description=Call echoes of warriors from the past to follow and defend you.
java_version=25

smartbrainlib_version=2.0.0
geckolib_version=5.5.2
