modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "Apache-2.0 AND LicenseRef-Echo-Warrior-Assets-1.0"
issueTrackerURL = "https://github.com/YurisCat/Echo-Warrior/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile = "assets/echo_warrior/icon.png"
credits = "${mod_credits}"
authors = "${mod_author}"
description = '''${mod_description}'''

[[mixins]]
config = "echo_warrior.mixins.json"

[[dependencies.echo_warrior]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.echo_warrior]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.echo_warrior]]
modId = "geckolib"
type = "required"
versionRange = "[${geckolib_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.echo_warrior]]
modId = "smartbrainlib"
type = "required"
versionRange = "[${smartbrainlib_version},)"
ordering = "NONE"
side = "BOTH"
